from collections.abc import Sequence
from typing import Protocol

from app.domain.accounts.entities import UserAccount


class UserAccountRepository(Protocol):
    def add(self, user: UserAccount) -> UserAccount: ...
    def update(self, user: UserAccount) -> UserAccount: ...
    def get(self, user_id: int) -> UserAccount | None: ...
    def get_by_email(self, email: str) -> UserAccount | None: ...
    def get_by_username(self, username: str) -> UserAccount | None: ...
    def list_all(self) -> Sequence[UserAccount]: ...
