from collections.abc import Sequence
from typing import Protocol

from app.domain.companies.entities import Company, CompanyMember


class CompanyRepository(Protocol):
    def add(self, company: Company) -> Company: ...
    def update(self, company: Company) -> Company: ...
    def get(self, company_id: int) -> Company | None: ...
    def get_by_name(self, name: str) -> Company | None: ...
    def get_by_join_code(self, join_code: str) -> Company | None: ...
    def list_all(self) -> Sequence[Company]: ...
    def list_pending(self) -> Sequence[Company]: ...


class CompanyMemberRepository(Protocol):
    def add(self, member: CompanyMember) -> CompanyMember: ...
    def update(self, member: CompanyMember) -> CompanyMember: ...
    def get(self, member_id: int) -> CompanyMember | None: ...
    def get_by_company_and_user(self, company_id: int, user_id: int) -> CompanyMember | None: ...
    def list_by_company(self, company_id: int) -> Sequence[CompanyMember]: ...
    def list_by_user(self, user_id: int) -> Sequence[CompanyMember]: ...
